### ISSUE TITLE
Support the `ppm` image format

### ISSUE THREAD

**Issue by SimonBrandner** [gabm/Satty#78] opened 2024-04-30 08:14 UTC
[Grim](https://sr.ht/~emersion/grim/) supports outputting images in the `ppm` image format which is much faster since it does not compress the data. It would be nice for Satty to support `ppm` as input since it would make the screenshot-taking process a bit faster

**Comment by gabm** [comment] 2024-04-30 08:18
nice observation! I realised the long loading times and suspected that it's png - but I didn't confirm that...

Mind contributing such a functionality?

**Comment by gabm** [comment] 2024-04-30 08:28
I think libvips might be a good option for iamge loading: https://github.com/olxgroup-oss/libvips-rust-bindings

**Comment by bpierre** [comment] 2024-07-30 13:39
It seems to work already?

```sh
grim -t ppm - | satty --filename -
```

**Comment by gabm** [comment] 2024-07-30 13:46
if that turns out to be true, maybe we can change the command in the readme file and add an explanation?

**Comment by gabm** [comment] 2024-08-16 07:44
I can confirm that it works.. its feels marginally faster.. I will close this issue and add a small note to the readme

**Closed by gabm** 2024-08-16 07:44 UTC
