### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by Ligthiago** [gabm/Satty#44] opened 2024-02-13 13:21 UTC
I tried this tool recently, it's good, but I and found some minor problems with it, which can probably be fixed.

**1) Dot at start of brush tool.**
No clue is this a my specific problem, maybe something with the touchpad, but the brush tool always starts with a dot that will not undo with line and stay as a separate item, so I need to tap CTRL-Z twice.
![dot](https://github.com/gabm/Satty/assets/142721811/539438f1-7ba0-4184-bc04-4fdc6fbf74aa)

**2) Sharp, almost polygonal curved lines.**
Brush tool with fast movements doesn't look very smooth. 
![image psd(2)](https://github.com/gabm/Satty/assets/142721811/673e471d-955b-4d69-8a89-5c7495d8b3d7)

**3) Lack of short options equivalents.**
Help message  right now is looks like this:
```
Modern Screenshot Annotation. A Screenshot Annotation Tool inspired by Swappy and Flameshot.

Usage: satty [OPTIONS] --filename <FILENAME>

Options:
  -c, --config <CONFIG>
          Path to the config file. Otherwise will be read from XDG_CONFIG_DIR/satty/config.toml
  -f, --filename <FILENAME>
          Path to input image or '-' to read from stdin
      --fullscreen
          Start Satty in fullscreen mode
      --output-filename <OUTPUT_FILENAME>
          Filename to use for saving action. Omit to disable saving to file. Might contain format specifiers: <https://docs.rs/chrono/latest/chrono/format/strftime/index.html>
      --early-exit
          Exit directly after copy/save action
      --initial-tool <TOOL>
          Select the tool on startup [aliases: init-tool] [possible values: pointer, crop, line, arrow, rectangle, text, marker, blur, brush]
      --copy-command <COPY_COMMAND>
          Configure the command to be called on copy, for example `wl-copy`
      --annotation-size-factor <ANNOTATION_SIZE_FACTOR>
          Increase or decrease the size of the annotations
  -h, --help
          Print help
  -V, --version
          Print version
```

As far as I can see, there are no short equivalents for very long `--output-filename` or `--annotation-size-factor` options. Probably `-o` for `--output-filename`, `-t` for `--initial-tool`, capital `-F` for `--fullscreen` would be nice and save a lot of time for typing. It just minor QOL improvement.

**PS.** Using last 0.9.0 version built from source on Hyprland

**Comment by gabm** [comment] 2024-02-15 05:06
Thank you so much for this detailed report.. All of them are problems, yes.

- 1) seems to be a small bug, I created an issue for it: #47
- 2) is because of two related issues: rendering is done synchronously in response to the input event (bad practise) and rendering is done on CPU only (that's cairos limitation). that means rendering is slow and therefore only a very low amount of input events is actually processed. I am working on a renderer using femtovg that would address both problems - but no eta so far.
- 3) is very very minor, I'll fix that soon

As always, any contribution is welcome!

**Comment by gabm** [comment] 2024-02-27 20:27
@Ligthiago once v0.11.0 is available for you, can you check that 1) and 2) are fixed?

**Comment by Ligthiago** [comment] 2024-02-27 21:51
1) Fixed for me
2) Much smoother, still some polygonal lines when moving the mouse really fast, but fine by me. Also, right now I can't check it on a HiDPI display like I did the first time.

Also while testing the new version I found another bug: after resizing window line is not drawn exactly under the cursor, check the video. But I think it's fine if you use it in fullscreen and don't change the window size or try to tile it.

https://github.com/gabm/Satty/assets/142721811/0bbaba35-990d-4bc8-9045-ba111f85a0de

**Comment by gabm** [comment] 2024-02-28 04:15
Thank you for testing and your report. Yes.. this is a regression introduced by #53...

**Comment by gabm** [comment] 2024-02-28 11:31
The fix to this regression has been released as v0.11.1. Can you check?

**Comment by Ligthiago** [comment] 2024-02-28 12:51
Fixed for me

**Comment by gabm** [comment] 2024-03-22 09:06
great!

**Closed by gabm** 2024-03-22 09:06 UTC
