### ISSUE TITLE
bug: Marker counter after undo action doesn't reset when called again

### ISSUE THREAD

**Issue by noornee** [gabm/satty#8] opened 2023-10-27 19:43 UTC
### Problem
I encountered an issue while using satty. 
If a user places a marker in the wrong spot and wants to remove it from that spot, the user does the undo action.
I noticed that after an undo action, when i try to place the marker in another position, the marker count is not reset, instead it increments
check video...

[satty-marker-undo-bug.webm](https://github.com/gabm/satty/assets/71889751/32b3db23-9b9f-4e40-b508-eeee3668c5c5)

### Solution

I figured i could declare a global mutable variable that kept count of the current marker number and decrements by 1 after every undo action.

I looked for a way to manage global variables and found that using the `lazy_static` crate provided a safer and cleaner way to manage global static variables.

I think i might have to switch to [once_cell](https://docs.rs/once_cell/latest/once_cell/)

**Comment by gabm** [comment] 2023-10-27 20:25
thank you so much for giving this a try.. but I'm afraid that this won't work on all circumstances..

a simple counter example is

- use the marker tool once - gives number 1
- use any other tool (e.g. arrow)
- undo the arrow
- create another marker - gives number 1 again!

Your solution is to create a global marker tool that is being used to track the number count - but using a local tool instance to do the "tool work"... that local instance works as before - except that it takes the number from the global instance...

Currently the architecture is, that tools create "drawables". Once the editing via the tool is finished, a drawable gets committed to the drawable stack in the sketchboard. Undo pops from the drawable stack and pushes to the redo stack, redo pops from the redo stack and pushes to the drawable stack.

By design, the sketchboard doesn't know anything about the workings of tools and drawables. That also means it doesn't know that popping a drawable may lead to side-effects such as decrementing a number. That should stay that way i think..

Without thinking it through, i believe the best approach would be to let the tool know that something has been reverted but another event.. this way the tool can then take proper action or choose to ignore it..

**Comment by gabm** [comment] 2023-10-27 20:34
I agree, that is a bug! As explained in the PR, i think we should introduce a dedicated undo/redo event that hands the drawable back to the tool and notifies it of those events

**Comment by gabm** [comment] 2023-10-31 10:55
I fixed this via a "hack".. I introduced a reference to the "next_number" counter in the tool inside the Marker and added a function to each drawable that notifies them about undo/redo events. On those events, the marker then manipulates the tools counter... I am not proud of this but it seems less invasive than other options.

[74880878c42fb7ef8fefbf2e5dcd50ccc556e91c](https://github.com/gabm/satty/commit/74880878c42fb7ef8fefbf2e5dcd50ccc556e91c)

The fix has been released with v0.3.0.

**Closed by gabm** 2023-10-31 10:55 UTC
