### ISSUE TITLE
[Bug] The blur tool doesn't blur the right part of the image if the window's size is changed

### ISSUE THREAD

**Issue by 00-kat** [gabm/Satty#83] opened 2024-05-12 13:43 UTC
This is quite a weird bug, so it's best if I demonstrate. Say I have a `wizard.jpg` open in satty:
![image](https://github.com/gabm/Satty/assets/65649991/9be2c076-7141-4d7a-a8c4-43c66fcd2988)
And now I blur the wizard's face:
![image](https://github.com/gabm/Satty/assets/65649991/0e7ff026-e072-4938-a3df-7da274938248)
Works fine!

Now, in fullscreen! Edit: changing the window's size also works, you don't *have* to go into fullscreen.
![image](https://github.com/gabm/Satty/assets/65649991/9ee053a6-4a3d-4045-a57f-d826824dabf6)
There's a black box there 😕
The problem is, the size of the image is used to grab the pixels to blur. Let's say I blur some white space:
![image](https://github.com/gabm/Satty/assets/65649991/b830bd11-ccfa-4420-9dbd-e521ac437677)
Obviously, it blurred *something*. That's not what was at that location though.

There are black squares since there were no pixels at the spot where the blur tool was grabbing the pixels to blur from. These black squares don't actually do anything after you copy/save the file, they just disappear, so in the end they don't end up hiding what you're trying to hide whatsoever.

**Comment by gabm** [comment] 2024-05-13 09:54
uff.. another coordinate system bug...good catch!

**Comment by gabm** [comment] 2024-05-14 13:24
Note: that was probably a satty bug. Mipmaps are generated during image creation and most likely not re-generated when the image is altered. That is why we see strange things happening, once scale is applied.. I removed mipmapping and the problem is gone

**Comment by 00-kat** [comment] 2024-05-14 13:38
(running off git using the AUR package `satty-git`, if that matters)

I was *about* to say it works in both windowed mode and fullscreen mode, but...
![image](https://github.com/gabm/Satty/assets/65649991/b91edc92-c020-4bd4-9a9a-02e67191fd66)
I drew a box around my profile picture with the blur tool and got that. So it seems the bug is still there, since fullscreen mode resizes the image as well (#81)

What I was originally planning to say is that resizing the window breaks it again, and it looks exactly like in the previous screenshot, except it's windowed mode.

**Comment by gabm** [comment] 2024-05-14 17:59
that is a pretty tough beast :) I'll check wether i can reproduce it

**Comment by gabm** [comment] 2024-05-14 18:00
is there some scaling (highdpi) involved?

**Comment by 00-kat** [comment] 2024-05-15 05:59
> is there some scaling (highdpi) involved?

Nope, 1.0x, but I can check on my laptop's screen to see if it's any different there.

**Comment by gabm** [comment] 2024-05-15 06:57
aaah now I see - the problem is when selecting a region *after* the window was resized.. .. not resizing the window after selecting..

**Comment by gabm** [comment] 2024-05-15 09:44
@00-kat can you confirm its fixed now?

**Closed** 2024-05-15 09:44 UTC

**Comment by 00-kat** [comment] 2024-05-15 09:50
Can confirm, it's fixed now!
